### ISSUE TITLE
Load errors with VOIP client (and alternative project)

### ISSUE THREAD

**Issue by goatchurchprime** [marc-weber1/godot_rtc_voip#1]
I couldn't get this working, having tried all the different combinations of WebRTC libraries.  Probably problems with the versioning

Meanwhile, there's this similar project that is potentially a good framework for handling the networking, including webrtc signalling through mqtt.  It would be neat to use it as a basis for the VOIP as well, once the libopus library has streaming functions.
    https://github.com/goatchurchprime/godot_multiplayer_networking_workbench/tree/v4.1

**Comment by marc-weber1** [comment]
The new version should be working soon: https://github.com/RevoluPowered/one-voip-godot-4
Watch the releases tab, we will put something there once it works on every platform :3
If u are in a rush & on windows DM me
